# Generated by Django 2.2.9 on 2020-02-02 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.TextField(max_length=264)),
                ('group_description', models.TextField(max_length=264)),
                ('group_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_published_date', models.DateTimeField(blank=True, null=True)),
                ('group_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
