# Generated by Django 2.2.3 on 2019-12-29 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(max_length=264)),
                ('post_text', models.TextField(max_length=264)),
                ('post_creation_date', models.DateTimeField(default=datetime.datetime(2019, 12, 29, 11, 53, 33, 183543, tzinfo=utc))),
                ('post_published_date', models.DateTimeField(blank=True, null=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=264)),
                ('comment_text', models.TextField(max_length=264)),
                ('comment_creation_date', models.DateTimeField(default=datetime.datetime(2019, 12, 29, 11, 53, 33, 184543, tzinfo=utc))),
                ('comment_approved', models.BooleanField(default=False)),
                ('comment_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_belong', to='blog_app.UserPostModel')),
            ],
        ),
    ]
