# Generated by Django 2.2.9 on 2020-02-02 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField(max_length=600)),
                ('post_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_published_date', models.DateTimeField(blank=True, null=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200)),
                ('comment_text', models.TextField(max_length=600)),
                ('comment_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_approved', models.BooleanField(default=False)),
                ('comment_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comment_belong', to='blog_app.UserPostModel')),
            ],
        ),
    ]
