# Generated by Django 2.2.3 on 2019-12-29 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentmodel',
            name='comment_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 29, 12, 8, 33, 231214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='post_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 29, 12, 8, 33, 230214, tzinfo=utc)),
        ),
    ]
