# Generated by Django 2.2.3 on 2020-01-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20191229_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentmodel',
            name='comment_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comment_belong', to='blog_app.UserPostModel'),
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='post_title',
            field=models.CharField(max_length=264),
        ),
    ]
