# Generated by Django 2.2.3 on 2020-01-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200101_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentmodel',
            name='comment_author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usercommentmodel',
            name='comment_text',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='post_text',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='post_title',
            field=models.CharField(max_length=200),
        ),
    ]
